version: '2.2'

services:
 commerce:
  build: 
    context: ./
    dockerfile: ./commerce/Dockerfile
    args:
      SQL_SA_PASSWORD: ${SQL_SA_PASSWORD}
      SQL_DB_PREFIX: ${SQL_DB_PREFIX}
      SOLR_PORT: ${SOLR_PORT}    
      SHOP_NAME: ${SHOP_NAME}
      ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
      COMMERCE_SIF_PACKAGE: ${COMMERCE_SIF_PACKAGE}
      COMMERCE_SDK_PACKAGE: ${COMMERCE_SDK_PACKAGE}
      SITECORE_BIZFX_PACKAGE: ${SITECORE_BIZFX_PACKAGE}
      SITECORE_IDENTITY_PACKAGE: ${SITECORE_IDENTITY_PACKAGE}
      COMMERCE_ENGINE_PACKAGE: ${COMMERCE_ENGINE_PACKAGE}
      COMMERCE_CERT_PATH: ${COMMERCE_CERT_PATH}
      ROOT_CERT_PATH: ${ROOT_CERT_PATH}
      SITECORE_CERT_PATH: ${SITECORE_CERT_PATH}
      SOLR_CERT_PATH: ${SOLR_CERT_PATH}
      XCONNECT_CERT_PATH: ${XCONNECT_CERT_PATH}
      PLUMBER_FILE_NAME: ${PLUMBER_FILE_NAME}
  volumes:
    - .\logs\commerce\CommerceAuthoring_Sc9:C:\inetpub\wwwroot\CommerceAuthoring_Sc9\wwwroot\logs
    - .\logs\commerce\CommerceMinions_Sc9:C:\inetpub\wwwroot\CommerceMinions_Sc9\wwwroot\logs
    - .\logs\commerce\CommerceOps_Sc9:C:\inetpub\wwwroot\CommerceOps_Sc9\wwwroot\logs
    - .\logs\commerce\CommerceShops_Sc9:C:\inetpub\wwwroot\CommerceShops_Sc9\wwwroot\logs
    - .\logs\commerce\SitecoreIdentityServer:C:\inetpub\wwwroot\SitecoreIdentityServer\wwwroot\logs
    - .\wwwroot\commerce:C:\Workspace
  depends_on:
    - xconnect
    - mssql
    - solr
    - sitecore
  networks:
    app_net:
      ipv4_address: 172.16.2.2

 mssql:
  build:
    context: ./
    dockerfile: ./mssql/Dockerfile
    args:
      DB_PREFIX: ${SQL_DB_PREFIX}
      COMMERCE_SDK_PACKAGE: ${COMMERCE_SDK_PACKAGE}
      COMMERCE_SIF_PACKAGE: ${COMMERCE_SIF_PACKAGE}
  environment:
    ACCEPT_EULA: "Y"
    sa_password: ${SQL_SA_PASSWORD}
  mem_limit: 2048m
  cpu_count: 4
  networks:
    app_net:
      ipv4_address: 172.16.2.3

 sitecore:
  build: 
    context: ./
    dockerfile: ./sitecore/Dockerfile
    args:
      COMMERCE_CERT_PATH: ${COMMERCE_CERT_PATH}
      COMMERCE_CONNECT_PACKAGE: ${COMMERCE_CONNECT_PACKAGE}
      WEB_TRANSFORM_TOOL: ${WEB_TRANSFORM_TOOL}
      COMMERCE_CONNECT_ENGINE_PACKAGE: ${COMMERCE_CONNECT_ENGINE_PACKAGE}
      COMMERCE_SIF_PACKAGE: ${COMMERCE_SIF_PACKAGE}
      ROOT_CERT_PATH: ${ROOT_CERT_PATH}
  volumes:
    - .\logs\sitecore:c:\inetpub\wwwroot\${SITECORE_SITE_NAME}\App_Data\logs
    - .\wwwroot\sitecore:C:\Workspace
  depends_on:
    - xconnect
    - mssql
    - solr
  cpu_count: 6
  networks:
    app_net:
      ipv4_address: 172.16.2.4

 solr:
  build:
    context: ./
    dockerfile: ./solr/Dockerfile
    args:
      HOST_NAME: ${SOLR_HOST_NAME}
      PORT: ${SOLR_PORT}
      SERVICE_NAME: ${SOLR_SERVICE_NAME}
      SITECORE_CORE_PREFIX: ${SITECORE_SOLR_CORE_PREFIX}
      COMMERCE_SIF_PACKAGE: ${COMMERCE_SIF_PACKAGE}
  ports:
    - ${SOLR_PORT}
  mem_limit: 4096m
  networks:
    app_net:
      ipv4_address: 172.16.2.5

 xconnect:
  build:
    context: ./
    dockerfile: ./xconnect/Dockerfile
  volumes:
    - .\logs\xconnect:C:\inetpub\wwwroot\xconnect\App_data\Logs
  depends_on:
    - mssql
    - solr
  networks:
    app_net:
      ipv4_address: 172.16.2.6
  cpu_count: 4

networks:
  app_net:
    ipam:
      driver: default
      config:
        -
          subnet: 172.16.2.0/24
          gateway: 172.16.2.1
          
